version: '3.8'
networks:
  dia_support_tools_dev_net:
    driver: bridge
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

services:
  sast:
    image: sonarqube:lts-community
    container_name: sast.$DOMAIN
    environment:
      SONAR_JDBC_URL: $DB_URL
      SONAR_JDBC_USERNAME: $DB_USERNAME
      SONAR_JDBC_PASSWORD: $DB_PASSWORD
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
      sonar.forceAuthentication: 'true'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9092:9092"
      - "36697:36697"
    networks:
      - sonarqube_demo_net
